version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    # ports:
    #   - 9000:80
      # - 3443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf